name: notaminfo

services:
    db:
        image: mysql:9
        ports:
            - 33062:3306
        expose: 
            - 3306
        environment:
            MYSQL_DATABASE: saved_notams
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_SSL_DISABLED: true
        volumes:
            - mysql_data:/var/lib/mysql 
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=12345678"]
            interval: 15s
            timeout: 20s
            retries: 10   
            start_period: 30s      
    redis:
        image: redis:alpine
        container_name: redis-container
        expose:
            - 6379
        ports:
            - 6379:6379
        restart: unless-stopped
        volumes:
            - redis_data:/data
    django:
        build:
            context: .
            dockerfile: notaminfo.Dockerfile  
        image: notaminfo
        command: sh -c "uv run manage.py makemigrations && uv run manage.py migrate && uv run manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/app/
            - /tmp/app/mysqld:/run/mysqld
        ports:
            - 8000:8000
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_started
        environment:
            DATABASE_URL: mysql://root:12345678@db:3306/saved_notams?useSSL=false
            CELERY_BROKER_URL: redis://redis:6379/1
    celery:
        image: notaminfo
        container_name: celery-container
        command: uv run celery -A config worker --loglevel=info
        depends_on:
        - django
        - redis
        environment:
            DATABASE_URL: mysql://root:12345678@db:3306/saved_notams?useSSL=false
            CELERY_BROKER_URL: redis://redis:6379/1

    beat:
        image: notaminfo
        container_name: beat-container
        command: uv run celery -A config beat --loglevel=info
        depends_on:
        - django
        - redis
        - celery
        environment:
            DATABASE_URL: mysql://root:12345678@db:3306/saved_notams?useSSL=false
            CELERY_BROKER_URL: redis://redis:6379/1

    flower:
        image: notaminfo
        container_name: flower-container
        command: uv run celery -A config flower --port=5555
        ports: 
            - 5555:5555
        depends_on:
        - django
        - redis
        - celery
        environment:
            DATABASE_URL: mysql://root:12345678@db:3306/saved_notams?useSSL=false
            CELERY_BROKER_URL: redis://redis:6379/1


volumes:
  mysql_data:
  redis_data: